#spring:
#  jpa:
#    properties:
#      hibernate:
#        format_sql: 'true'
#    show-sql: 'true'
##    database: mysql
##    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

spring:
  session:
    jdbc:
      initialize-schema: always
    store-type: jdbc
#  datasource:
#    driver-class-name: org.h2.Driver
#    # username: sa
#    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
    ddl-auto: update