#spring:
#  jpa:
#    properties:
#      hibernate:
#        format_sql: 'true'
#    show-sql: 'true'
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher