INSERT INTO STORE_OPEN_DAY VALUES(1, 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE','TRUE','TRUE');
INSERT INTO STORE (CREATED_AT, MODIFIED_AT, ADDRESS, CLOSE_TIME, IMAGE_URL, LATITUDE, LONGITUDE, NAME, OPEN_TIME, STORE_OPEN_DAY_ID) VALUES (now(), now(), '주소', '17:00:00', 'img1.png', 126.926562890712, 37.5612680228642, '매장1', '08:00:00', 1);

INSERT INTO DRESS_OPTION (NAME) VALUES ('색상');
INSERT INTO DRESS_OPTION (NAME) VALUES ('사이즈');
INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '아우터' ,'설명', '아우터 1-1', 100000, 1, 2, 1);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (1);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (1);

INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '아우터' ,'설명', '아우터 1-2', 110000, 1, 2, 1);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (2);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (2);

INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '아우터' ,'설명', '아우터 1-3', 110000, 1, 2, 1);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (3);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (3);

INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '상의' ,'설명', '상의 1-1', 50000, 1, 2, 1);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (4);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (4);

INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '상의' ,'설명', '상의 1-2', 50000, 1, 2, 1);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (5);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (5);

INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '상의' ,'설명', '상의 1-3', 50000, 1, 2, 1);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (6);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (6);

INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '상의' ,'설명', '상의 1-4', 50000, 1, 2, 1);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (7);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (7);

INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '하의' ,'설명', '하의 1-1', 30000, 1, 2, 1);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (8);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (8);


INSERT INTO STORE_OPEN_DAY VALUES(2, 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE','TRUE','TRUE');
INSERT INTO STORE (CREATED_AT, MODIFIED_AT, ADDRESS, CLOSE_TIME, IMAGE_URL, LATITUDE, LONGITUDE, NAME, OPEN_TIME, STORE_OPEN_DAY_ID) VALUES (now(), now(), '주소', '17:00:00', 'img2.png', 127.013183004498, 37.5912680228642, '매장2', '08:00:00', 2);

INSERT INTO DRESS_OPTION (NAME) VALUES ('색상');
INSERT INTO DRESS_OPTION (NAME) VALUES ('사이즈');
INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '아우터' ,'설명', '아우터 2-1', 100000, 1, 2, 2);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (9);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (9);

INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '아우터' ,'설명', '아우터 2-2', 110000, 1, 2, 2);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (10);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (10);

INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '아우터' ,'설명', '아우터 2-3', 110000, 1, 2, 2);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (11);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (11);

INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '상의' ,'설명', '상의 2-1', 50000, 1, 2, 2);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (12);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (12);

INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '상의' ,'설명', '상의 2-2', 50000, 1, 2, 2);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (13);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (13);

INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '상의' ,'설명', '상의 2-3', 50000, 1, 2, 2);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (14);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (14);

INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '상의' ,'설명', '상의 2-4', 50000, 1, 2, 2);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (15);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (15);

INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '하의' ,'설명', '하의 2-1', 30000, 1, 2, 2);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (16);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (16);

INSERT INTO STORE_OPEN_DAY VALUES(3, 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE','TRUE','TRUE');
INSERT INTO STORE (CREATED_AT, MODIFIED_AT, ADDRESS, CLOSE_TIME, IMAGE_URL, LATITUDE, LONGITUDE, NAME, OPEN_TIME, STORE_OPEN_DAY_ID) VALUES (now(), now(), '주소', '17:00:00', 'img3.png', 127.013183004498, 37.5920844922334, '매장3', '08:00:00', 3);

INSERT INTO DRESS_OPTION (NAME) VALUES ('색상');
INSERT INTO DRESS_OPTION (NAME) VALUES ('사이즈');
INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '아우터' ,'설명', '아우터 3-1', 100000, 1, 2, 3);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (17);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (17);

INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '아우터' ,'설명', '아우터 3-2', 110000, 1, 2, 3);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (18);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (18);

INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '아우터' ,'설명', '아우터 3-3', 110000, 1, 2, 3);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (19);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (19);

INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '상의' ,'설명', '상의 3-1', 50000, 1, 2, 3);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (20);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (20);

INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '상의' ,'설명', '상의 3-2', 50000, 1, 2, 3);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (21);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (21);

INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '상의' ,'설명', '상의 3-3', 50000, 1, 2, 3);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (22);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (22);

INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '상의' ,'설명', '상의 3-4', 50000, 1, 2, 3);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (23);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (23);

INSERT INTO DRESS (CREATED_AT, MODIFIED_AT, CATEGORY, COMMENT, NAME, PRICE, DRESS_OPTION1_ID, DRESS_OPTION2_ID, STORE_ID) VALUES (now(), now(), '하의' ,'설명', '하의 3-1', 30000, 1, 2, 3);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (24);
INSERT INTO DRESS_IMAGE (DRESS_ID) VALUES (24);